#pragma once

#include <touchgfx/containers/Container.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/canvas/Canvas.hpp>
#include <touchgfx/widgets/canvas/Circle.hpp>

// forward declarations for helper widgets
#include "widgets/ArcGauge.hpp"
#include "widgets/FillBar.hpp"
// alarm overlay
#include "../alarm/AlarmOverlay.hpp"

/*
 * Base class generated by TouchGFX Designer.  Only minimal stub is provided
 * here so that the project compiles; the Designer will normally supply a
 * richer class with layout and widget members.
 */
class MainViewBase : public touchgfx::Container {
public:
    virtual void setupScreen() {}
    virtual void tearDownScreen() {}
};

/**
 * Implementation of the main dashboard screen.  Contains all widgets needed
 * for the RPM gauge, speed, gear, etc.  The setters below update widget
 * state and invalidate changed regions.
 */
class MainView : public MainViewBase {
public:
    MainView();
    virtual ~MainView() {}

    void setupScreen() override;
    void tearDownScreen() override;

    void setRPM(uint16_t rpm);
    void setSpeed(float kmh);
    void setGear(uint16_t gear);
    void setCoolantTemp(float c);
    void setOilPressure(float kpa);
    void setWarnings(bool revlimit, bool knock, bool launch, bool antilag, bool shiftcut);
    void setCANTimeout(bool timeout);

private:
    // widgets
    ArcGauge rpmGauge;
    touchgfx::TextArea rpmText;
    touchgfx::TextArea rpmUnit;
    touchgfx::TextArea speedText;
    touchgfx::TextArea speedUnit;
    touchgfx::TextArea gearText;
    touchgfx::TextArea gearLabel;
    FillBar throttleBar;
    touchgfx::TextArea throttleLabel;
    touchgfx::TextArea throttleValue;
    touchgfx::TextArea lambdaAvgText;
    touchgfx::TextArea lambdaAvgLabel;
    FillBar coolantTempBar;
    touchgfx::TextArea coolantLabel;
    FillBar oilPressureBar;
    touchgfx::TextArea oilPressureLabel;
    
    // wildcard buffers for textareas
    wchar_t rpmTextBuffer[16];
    wchar_t speedTextBuffer[16];
    wchar_t gearTextBuffer[8];
    wchar_t throttleTextBuffer[16];
    wchar_t lambdaTextBuffer[16];
    wchar_t coolantTextBuffer[16];
    wchar_t oilPressureTextBuffer[16];
    // warning pills
    touchgfx::Box warningPills[5];
    touchgfx::TextArea warningTexts[5];
    touchgfx::FadeAnimator warningAlpha[5];
    touchgfx::Box timeoutOverlay;
    touchgfx::TextArea timeoutText;
    touchgfx::TextArea timeoutSubtext;

    // last states to avoid unnecessary invalidation
    uint16_t lastRPM;
    float lastSpeed;
    uint16_t lastGear;
    float lastCoolant;
    float lastOilPressure;
    bool lastCanTimeout;

    // overlay for active alarms
    AlarmOverlay m_alarmOverlay;

public:
    /**
     * Trigger the alarm overlay tick (called by presenter after evaluating).
     */
    void updateAlarmOverlay() { m_alarmOverlay.tick(); }
};
